### ISSUE TITLE
api.veracode.io not supported

### ISSUE THREAD

**Issue by tjarrettveracode** [ctcampbell/insomnia-plugin-veracode-hmac#1]
Some older Veracode APIs (e.g. eLearning) are still documented as being homed at https://api.veracode.io. Can the plugin.js be updated to include this as an alternate hostname?

Test verification: 

1. Create a new Insomnia request that hits https://api.veracode.io/elearning/v1/courses. _HMAC auth is not applied but should be_
2. Change the URL to https://api.veracode.com/elearning/v1/courses. _HMAC auth is applied_

**Comment by ctcampbell** [comment]
Fixed, now supports api.veracode.com, api.veracode.io and analysiscenter.veracode.com
